# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: minion 0.1.17 ruby lib

Gem::Specification.new do |s|
  s.name = "minion"
  s.version = "0.1.17"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Orion Henry"]
  s.date = "2015-08-25"
  s.description = "Super simple job queue over AMQP"
  s.email = "orion@heroku.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/minion.rb",
    "lib/minion/handler.rb",
    "minion.gemspec",
    "spec/base.rb",
    "spec/enqueue_spec.rb"
  ]
  s.homepage = "http://github.com/orionz/minion"
  s.rubyforge_project = "minion"
  s.rubygems_version = "2.4.8"
  s.summary = "Super simple job queue over AMQP"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
<<<<<<< HEAD
      s.add_runtime_dependency(%q<amq-protocol>, ["~> 1.9.2"])
      s.add_runtime_dependency(%q<amqp>, [">= 1.3.0"])
      s.add_runtime_dependency(%q<bunny>, ["~> 1.1.3"])
      s.add_runtime_dependency(%q<json>, [">= 1.2.0"])
    else
      s.add_dependency(%q<amq-protocol>, ["~> 1.9.2"])
      s.add_dependency(%q<amqp>, [">= 1.3.0"])
=======
      s.add_runtime_dependency(%q<amqp>, ["~> 1.3.0"])
      s.add_runtime_dependency(%q<bunny>, ["~> 1.1.3"])
      s.add_runtime_dependency(%q<json>, [">= 1.2.0"])
    else
      s.add_dependency(%q<amqp>, ["~> 1.3.0"])
>>>>>>> 7732b999e63c608ccd4db93895aae16776ade9b8
      s.add_dependency(%q<bunny>, ["~> 1.1.3"])
      s.add_dependency(%q<json>, [">= 1.2.0"])
    end
  else
<<<<<<< HEAD
    s.add_dependency(%q<amq-protocol>, ["~> 1.9.2"])
    s.add_dependency(%q<amqp>, [">= 1.3.0"])
=======
    s.add_dependency(%q<amqp>, ["~> 1.3.0"])
>>>>>>> 7732b999e63c608ccd4db93895aae16776ade9b8
    s.add_dependency(%q<bunny>, ["~> 1.1.3"])
    s.add_dependency(%q<json>, [">= 1.2.0"])
  end
end

